name: reactive-resume-start-dev

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgbouncer:
    image: edoburu/pgbouncer:latest
    restart: unless-stopped
    ports:
      - "65432:5432"
    environment:
      POOL_MODE: transaction
      AUTH_TYPE: scram-sha-256
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # rustfs:
  #   image: rustfs/rustfs:latest
  #   restart: unless-stopped
  #   security_opt:
  #     - "no-new-privileges:true"
  #   ports:
  #     - "9100:9000" # S3 API
  #     - "9101:9001" # Admin UI
  #   environment:
  #     - RUSTFS_CONSOLE_ENABLE=true
  #     - RUSTFS_ACCESS_KEY=rustfs
  #     - RUSTFS_SECRET_KEY=rustfs
  #   volumes:
  #     - rustfs_data:/data
  #   healthcheck:
  #     test:
  #       [
  #         "CMD",
  #         "sh",
  #         "-c",
  #         "curl -f http://localhost:9000/health && curl -f http://localhost:9001/health",
  #       ]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  seaweedfs:
    image: chrislusf/seaweedfs:latest
    restart: unless-stopped
    command: server -s3 -filer -dir=/data -ip=0.0.0.0
    ports:
      - "8333:8333" # S3 API
      - "8888:8888" # Filer API
    environment:
      - AWS_ACCESS_KEY_ID=seaweedfs
      - AWS_SECRET_ACCESS_KEY=seaweedfs
    volumes:
      - seaweedfs_data:/data
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:8888"]
      interval: 30s
      timeout: 10s
      retries: 3

  seaweedfs-create-bucket:
    image: quay.io/minio/mc:latest
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set seaweedfs http://seaweedfs:8333 seaweedfs seaweedfs;
        mc mb seaweedfs/reactive-resume-start;
        exit 0;
      "
    depends_on:
      seaweedfs:
        condition: service_healthy

  gotenberg:
    image: gotenberg/gotenberg:edge
    restart: unless-stopped
    ports:
      - "4000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - CHROMIUM_AUTO_START=true
      - LIBREOFFICE_DISABLE_ROUTES=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - TZ=UTC
      - NODE_ENV=development
      # App
      - APP_URL=http://localhost:3000
      - PRINTER_APP_URL=http://app:3000
      # Printer
      - GOTENBERG_ENDPOINT=http://gotenberg:3000
      # Database
      - DATABASE_URL=postgresql://postgres:postgres@pgbouncer:5432/postgres
      # Auth
      - AUTH_SECRET=this-is-a-super-secret-key
      # Storage
      - S3_ACCESS_KEY_ID=seaweedfs
      - S3_SECRET_ACCESS_KEY=seaweedfs
      - S3_ENDPOINT=http://localhost:8333
      - S3_BUCKET=reactive-resume-start
    volumes:
      # Mount source code for hot reload (exclude node_modules for performance)
      - ./src:/app/src:delegated
      - ./public:/app/public:delegated
      - ./locales:/app/locales:delegated
      - ./migrations:/app/migrations:delegated
      - ./scripts:/app/scripts:delegated
      - ./plugins:/app/plugins:delegated
      - ./data:/app/data
      # Mount config files that might change
      - ./package.json:/app/package.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./vite.config.ts:/app/vite.config.ts:ro
      - ./biome.json:/app/biome.json:ro
      - ./lingui.config.ts:/app/lingui.config.ts:ro
      - ./drizzle.config.ts:/app/drizzle.config.ts:ro
      - ./components.json:/app/components.json:ro
      # Preserve node_modules in container (not mounted)
      - /app/node_modules
    depends_on:
      pgbouncer:
        condition: service_healthy
      seaweedfs:
        condition: service_healthy
      seaweedfs-create-bucket:
        condition: service_completed_successfully

volumes:
  # rustfs_data:
  postgres_data:
  seaweedfs_data:
