/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as DashboardRouteRouteImport } from "./routes/dashboard/route";
import { Route as AuthRouteRouteImport } from "./routes/auth/route";
import { Route as HomeRouteRouteImport } from "./routes/_home/route";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index";
import { Route as AuthIndexRouteImport } from "./routes/auth/index";
import { Route as HomeIndexRouteImport } from "./routes/_home/index";
import { Route as AuthVerify2faRouteImport } from "./routes/auth/verify-2fa";
import { Route as AuthResetPasswordRouteImport } from "./routes/auth/reset-password";
import { Route as AuthRegisterRouteImport } from "./routes/auth/register";
import { Route as AuthLoginRouteImport } from "./routes/auth/login";
import { Route as AuthForgotPasswordRouteImport } from "./routes/auth/forgot-password";
import { Route as ApiHealthRouteImport } from "./routes/api/health";
import { Route as ApiSplatRouteImport } from "./routes/api/$";
import { Route as BuilderResumeIdRouteRouteImport } from "./routes/builder/$resumeId/route";
import { Route as DashboardResumesIndexRouteImport } from "./routes/dashboard/resumes/index";
import { Route as BuilderResumeIdIndexRouteImport } from "./routes/builder/$resumeId/index";
import { Route as DashboardSettingsProfileRouteImport } from "./routes/dashboard/settings/profile";
import { Route as DashboardSettingsPreferencesRouteImport } from "./routes/dashboard/settings/preferences";
import { Route as DashboardSettingsDangerZoneRouteImport } from "./routes/dashboard/settings/danger-zone";
import { Route as DashboardSettingsAiRouteImport } from "./routes/dashboard/settings/ai";
import { Route as ApiRpcSplatRouteImport } from "./routes/api/rpc.$";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth.$";
import { Route as DashboardSettingsAuthenticationIndexRouteImport } from "./routes/dashboard/settings/authentication/index";

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any);
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: "/_home",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthRouteRoute,
} as any);
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => HomeRouteRoute,
} as any);
const AuthVerify2faRoute = AuthVerify2faRouteImport.update({
  id: "/verify-2fa",
  path: "/verify-2fa",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => AuthRouteRoute,
} as any);
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: "/api/health",
  path: "/api/health",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: "/api/$",
  path: "/api/$",
  getParentRoute: () => rootRouteImport,
} as any);
const BuilderResumeIdRouteRoute = BuilderResumeIdRouteRouteImport.update({
  id: "/builder/$resumeId",
  path: "/builder/$resumeId",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardResumesIndexRoute = DashboardResumesIndexRouteImport.update({
  id: "/resumes/",
  path: "/resumes/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const BuilderResumeIdIndexRoute = BuilderResumeIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => BuilderResumeIdRouteRoute,
} as any);
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: "/settings/profile",
    path: "/settings/profile",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardSettingsPreferencesRoute =
  DashboardSettingsPreferencesRouteImport.update({
    id: "/settings/preferences",
    path: "/settings/preferences",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardSettingsDangerZoneRoute =
  DashboardSettingsDangerZoneRouteImport.update({
    id: "/settings/danger-zone",
    path: "/settings/danger-zone",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardSettingsAiRoute = DashboardSettingsAiRouteImport.update({
  id: "/settings/ai",
  path: "/settings/ai",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: "/api/rpc/$",
  path: "/api/rpc/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardSettingsAuthenticationIndexRoute =
  DashboardSettingsAuthenticationIndexRouteImport.update({
    id: "/settings/authentication/",
    path: "/settings/authentication/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/auth": typeof AuthRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/builder/$resumeId": typeof BuilderResumeIdRouteRouteWithChildren;
  "/api/$": typeof ApiSplatRoute;
  "/api/health": typeof ApiHealthRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/register": typeof AuthRegisterRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/verify-2fa": typeof AuthVerify2faRoute;
  "/": typeof HomeIndexRoute;
  "/auth/": typeof AuthIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/dashboard/settings/ai": typeof DashboardSettingsAiRoute;
  "/dashboard/settings/danger-zone": typeof DashboardSettingsDangerZoneRoute;
  "/dashboard/settings/preferences": typeof DashboardSettingsPreferencesRoute;
  "/dashboard/settings/profile": typeof DashboardSettingsProfileRoute;
  "/builder/$resumeId/": typeof BuilderResumeIdIndexRoute;
  "/dashboard/resumes": typeof DashboardResumesIndexRoute;
  "/dashboard/settings/authentication": typeof DashboardSettingsAuthenticationIndexRoute;
}
export interface FileRoutesByTo {
  "/api/$": typeof ApiSplatRoute;
  "/api/health": typeof ApiHealthRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/register": typeof AuthRegisterRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/verify-2fa": typeof AuthVerify2faRoute;
  "/": typeof HomeIndexRoute;
  "/auth": typeof AuthIndexRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/dashboard/settings/ai": typeof DashboardSettingsAiRoute;
  "/dashboard/settings/danger-zone": typeof DashboardSettingsDangerZoneRoute;
  "/dashboard/settings/preferences": typeof DashboardSettingsPreferencesRoute;
  "/dashboard/settings/profile": typeof DashboardSettingsProfileRoute;
  "/builder/$resumeId": typeof BuilderResumeIdIndexRoute;
  "/dashboard/resumes": typeof DashboardResumesIndexRoute;
  "/dashboard/settings/authentication": typeof DashboardSettingsAuthenticationIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_home": typeof HomeRouteRouteWithChildren;
  "/auth": typeof AuthRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/builder/$resumeId": typeof BuilderResumeIdRouteRouteWithChildren;
  "/api/$": typeof ApiSplatRoute;
  "/api/health": typeof ApiHealthRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/register": typeof AuthRegisterRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/verify-2fa": typeof AuthVerify2faRoute;
  "/_home/": typeof HomeIndexRoute;
  "/auth/": typeof AuthIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/dashboard/settings/ai": typeof DashboardSettingsAiRoute;
  "/dashboard/settings/danger-zone": typeof DashboardSettingsDangerZoneRoute;
  "/dashboard/settings/preferences": typeof DashboardSettingsPreferencesRoute;
  "/dashboard/settings/profile": typeof DashboardSettingsProfileRoute;
  "/builder/$resumeId/": typeof BuilderResumeIdIndexRoute;
  "/dashboard/resumes/": typeof DashboardResumesIndexRoute;
  "/dashboard/settings/authentication/": typeof DashboardSettingsAuthenticationIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/auth"
    | "/dashboard"
    | "/builder/$resumeId"
    | "/api/$"
    | "/api/health"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/register"
    | "/auth/reset-password"
    | "/auth/verify-2fa"
    | "/"
    | "/auth/"
    | "/dashboard/"
    | "/api/auth/$"
    | "/api/rpc/$"
    | "/dashboard/settings/ai"
    | "/dashboard/settings/danger-zone"
    | "/dashboard/settings/preferences"
    | "/dashboard/settings/profile"
    | "/builder/$resumeId/"
    | "/dashboard/resumes"
    | "/dashboard/settings/authentication";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/api/$"
    | "/api/health"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/register"
    | "/auth/reset-password"
    | "/auth/verify-2fa"
    | "/"
    | "/auth"
    | "/dashboard"
    | "/api/auth/$"
    | "/api/rpc/$"
    | "/dashboard/settings/ai"
    | "/dashboard/settings/danger-zone"
    | "/dashboard/settings/preferences"
    | "/dashboard/settings/profile"
    | "/builder/$resumeId"
    | "/dashboard/resumes"
    | "/dashboard/settings/authentication";
  id:
    | "__root__"
    | "/_home"
    | "/auth"
    | "/dashboard"
    | "/builder/$resumeId"
    | "/api/$"
    | "/api/health"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/register"
    | "/auth/reset-password"
    | "/auth/verify-2fa"
    | "/_home/"
    | "/auth/"
    | "/dashboard/"
    | "/api/auth/$"
    | "/api/rpc/$"
    | "/dashboard/settings/ai"
    | "/dashboard/settings/danger-zone"
    | "/dashboard/settings/preferences"
    | "/dashboard/settings/profile"
    | "/builder/$resumeId/"
    | "/dashboard/resumes/"
    | "/dashboard/settings/authentication/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  HomeRouteRoute: typeof HomeRouteRouteWithChildren;
  AuthRouteRoute: typeof AuthRouteRouteWithChildren;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  BuilderResumeIdRouteRoute: typeof BuilderResumeIdRouteRouteWithChildren;
  ApiSplatRoute: typeof ApiSplatRoute;
  ApiHealthRoute: typeof ApiHealthRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth": {
      id: "/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_home": {
      id: "/_home";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof HomeRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/auth/": {
      id: "/auth/";
      path: "/";
      fullPath: "/auth/";
      preLoaderRoute: typeof AuthIndexRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_home/": {
      id: "/_home/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof HomeIndexRouteImport;
      parentRoute: typeof HomeRouteRoute;
    };
    "/auth/verify-2fa": {
      id: "/auth/verify-2fa";
      path: "/verify-2fa";
      fullPath: "/auth/verify-2fa";
      preLoaderRoute: typeof AuthVerify2faRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/reset-password": {
      id: "/auth/reset-password";
      path: "/reset-password";
      fullPath: "/auth/reset-password";
      preLoaderRoute: typeof AuthResetPasswordRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/register": {
      id: "/auth/register";
      path: "/register";
      fullPath: "/auth/register";
      preLoaderRoute: typeof AuthRegisterRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/login": {
      id: "/auth/login";
      path: "/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/forgot-password": {
      id: "/auth/forgot-password";
      path: "/forgot-password";
      fullPath: "/auth/forgot-password";
      preLoaderRoute: typeof AuthForgotPasswordRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/api/health": {
      id: "/api/health";
      path: "/api/health";
      fullPath: "/api/health";
      preLoaderRoute: typeof ApiHealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/$": {
      id: "/api/$";
      path: "/api/$";
      fullPath: "/api/$";
      preLoaderRoute: typeof ApiSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/builder/$resumeId": {
      id: "/builder/$resumeId";
      path: "/builder/$resumeId";
      fullPath: "/builder/$resumeId";
      preLoaderRoute: typeof BuilderResumeIdRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/resumes/": {
      id: "/dashboard/resumes/";
      path: "/resumes";
      fullPath: "/dashboard/resumes";
      preLoaderRoute: typeof DashboardResumesIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/builder/$resumeId/": {
      id: "/builder/$resumeId/";
      path: "/";
      fullPath: "/builder/$resumeId/";
      preLoaderRoute: typeof BuilderResumeIdIndexRouteImport;
      parentRoute: typeof BuilderResumeIdRouteRoute;
    };
    "/dashboard/settings/profile": {
      id: "/dashboard/settings/profile";
      path: "/settings/profile";
      fullPath: "/dashboard/settings/profile";
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings/preferences": {
      id: "/dashboard/settings/preferences";
      path: "/settings/preferences";
      fullPath: "/dashboard/settings/preferences";
      preLoaderRoute: typeof DashboardSettingsPreferencesRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings/danger-zone": {
      id: "/dashboard/settings/danger-zone";
      path: "/settings/danger-zone";
      fullPath: "/dashboard/settings/danger-zone";
      preLoaderRoute: typeof DashboardSettingsDangerZoneRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings/ai": {
      id: "/dashboard/settings/ai";
      path: "/settings/ai";
      fullPath: "/dashboard/settings/ai";
      preLoaderRoute: typeof DashboardSettingsAiRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/api/rpc/$": {
      id: "/api/rpc/$";
      path: "/api/rpc/$";
      fullPath: "/api/rpc/$";
      preLoaderRoute: typeof ApiRpcSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/settings/authentication/": {
      id: "/dashboard/settings/authentication/";
      path: "/settings/authentication";
      fullPath: "/dashboard/settings/authentication";
      preLoaderRoute: typeof DashboardSettingsAuthenticationIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
  }
}

interface HomeRouteRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute;
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
};

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
);

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthRegisterRoute: typeof AuthRegisterRoute;
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute;
  AuthVerify2faRoute: typeof AuthVerify2faRoute;
  AuthIndexRoute: typeof AuthIndexRoute;
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerify2faRoute: AuthVerify2faRoute,
  AuthIndexRoute: AuthIndexRoute,
};

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
);

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute;
  DashboardSettingsAiRoute: typeof DashboardSettingsAiRoute;
  DashboardSettingsDangerZoneRoute: typeof DashboardSettingsDangerZoneRoute;
  DashboardSettingsPreferencesRoute: typeof DashboardSettingsPreferencesRoute;
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute;
  DashboardResumesIndexRoute: typeof DashboardResumesIndexRoute;
  DashboardSettingsAuthenticationIndexRoute: typeof DashboardSettingsAuthenticationIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSettingsAiRoute: DashboardSettingsAiRoute,
  DashboardSettingsDangerZoneRoute: DashboardSettingsDangerZoneRoute,
  DashboardSettingsPreferencesRoute: DashboardSettingsPreferencesRoute,
  DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
  DashboardResumesIndexRoute: DashboardResumesIndexRoute,
  DashboardSettingsAuthenticationIndexRoute:
    DashboardSettingsAuthenticationIndexRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

interface BuilderResumeIdRouteRouteChildren {
  BuilderResumeIdIndexRoute: typeof BuilderResumeIdIndexRoute;
}

const BuilderResumeIdRouteRouteChildren: BuilderResumeIdRouteRouteChildren = {
  BuilderResumeIdIndexRoute: BuilderResumeIdIndexRoute,
};

const BuilderResumeIdRouteRouteWithChildren =
  BuilderResumeIdRouteRoute._addFileChildren(BuilderResumeIdRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  HomeRouteRoute: HomeRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  BuilderResumeIdRouteRoute: BuilderResumeIdRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
